### ISSUE TITLE
Error when installing linux-surfacepro3-headers

### ISSUE THREAD

**Issue by ianks** [matthewwardrop/linux-surfacepro3#11] opened 2015-10-19 15:18 UTC
When attempting to install the headers, I get this error:

```
==> Entering fakeroot environment...
==> Starting package_linux-surfacepro3-headers()...
cp: cannot stat ‘arch//Makefile’: No such file or directory
==> ERROR: A failure occurred in package_linux-surfacepro3-headers().
    Aborting...
==> ERROR: Makepkg was unable to build linux-surfacepro3.
==> Restart building linux-surfacepro3-headers ? [y/N]
==> --------------------------------------------------
==> 
==> ERROR: unable to update
```

**Comment by matthewwardrop** [comment] 2015-10-25 03:47
Hi ianks. I cannot reproduce that here. Does this still happen for you?

**Comment by matthewwardrop** [comment] 2015-11-13 21:20
Closing. Feel free to reopen this issue if it is still a problem :).

**Closed as completed by matthewwardrop** 2015-11-13 21:20 UTC

**Comment by frebib** [comment] 2015-11-26 18:59
Can confirm, this happens for me too. Just spent 2 hours waiting to be greeted by this error

**Comment by matthewwardrop** [comment] 2015-11-26 22:54
I just recompiled the kernel in about half an hour (using export MAKE='make -j3') and was able to install the kernel headers without any difficulty. I'm not sure why there is a difference between our experiences, but I cannot really do much about it unless I can reproduce it. :(

**Comment by frebib** [comment] 2015-11-26 23:54
I got the errors the first time when trying to install the headers from the Aur package. Trying again now as you suggest, using export MAKE='make -j3' then makepkg, I presume that is what you mean. It appears to be chugging slightly quicker this time so fingers crossed that alias makes a difference. Strangely the headers weren't put in my boot directory the first time I installed the base package from the Aur, I'm not sure why. Will let you know how it goes and hopefully it doesn't take too long

**Comment by frebib** [comment] 2015-11-27 00:58
Worked like a charm, thanks! Tooks about an hour on my i5 SP3 while doing other stuff so not too bad

**Comment by matthewwardrop** [comment] 2015-11-27 01:07
Excellent :). In case you weren't aware, specifying MAKE as 'make -j3' asks the make system to compile on three threads simultaneously, rather than just one. I typically choose a number of threads one less than the number of cores on the machine I'm compiling (unless I'm not going to be otherwise using the machine).

However, it really shouldn't change whether the build works or not... so your reported issue remains perplexing.

Let me know if you get into trouble again :).
